### ISSUE TITLE
[Support] Brotli compression setup

### ISSUE THREAD

**Issue by sathyarajshetigar** [TheSleepyKoala/Svelcordity#4]
How to make it work if the compression is set to Brotli? With this method we don't get loader JS or any other files that we need to set up in "initializeUnity" method

**Comment by Chizaruu** [comment]
I don't know what you are talking about, Unity generates all the brotli compressed files.
![image](https://github.com/user-attachments/assets/5dc23ed6-481e-4eac-a9ef-9ade752cf74d)

**Comment by sathyarajshetigar** [comment]
Oops, Yes Did a clean build and now it looks as expected. Some postprocessor was interrupting the build.
